import Custom from "@/components/Custom/Custom";
import NavbarCustom from "@/components/Navbar/NavbarCustom";
import Head from "next/head";
import React from "react";

function CustomY() {
  return (
    <>
      <div>
        <Head>
          <title>Design Your Model Y | Tesla</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/icon.png" />
        </Head>
      </div>

      <main>
        <NavbarCustom />
        <Custom
          bgImageOne="ModelYCustom.jpeg"
          bgImageTwo="ModelYCustom2.jpeg"
          bgImageThree="ModelYCustom3.jpeg"
          bonus="$7,500 Federal Tax Credit New Model 3 and Model Y vehicles qualify for a federal tax credit for eligible buyers. This $7,500 credit is in effect for deliveries taken before an update to the federal guidance, which Treasury and the IRS intend to issue no later than March 31, 2023.See Details"
          title="Model Y"
          btnCenter="Continue to Payment"
          delivery="Est. Delivery: Apr – Jun 2023"
          range="330mi"
          subRange="Range (EPA est.)"
          speed="135mph"
          subSpeed="Top Speed"
          seconds="4.8sec"
          subSeconds="0-60 mph"
          price="$ 54,990 Vehicle Price "
          subPrice="$ 40,090 After Potential Savings"
        />
      </main>
    </>
  );
}

export default CustomY;
