"use client";

import Main from "../components/Main/Main";
import React from "react";
import Navbar from "@/components/Navbar/Navbar";
import Head from "next/head";

function page() {
  return (
    <>
      <Head>
        <title>Electric Cars, Solar & deClean Energy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <main>
        <Navbar />
        <Main />
      </main>
    </>
  );
}

export default page;
