"use client";

import NavbarShop from "../components/Navbar/NavbarShop";
import ShopCarousel from "../components/Shop/ShopCarousel";
import SliderShop from "../components/Shop/SliderShop";
import SectionShopReducers from "../components/Shop/SectionShop";
import Head from "next/head";
import React from "react";

export default function Shop() {
  return (
    <>
      <Head>
        <title>The Official Tesla Shop | Tesla</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>

      <main>
        <NavbarShop />
        <div className="absolute top-0 right-0 left-0">
          <ShopCarousel />
          <SliderShop />
          <SectionShopReducers />
        </div>
      </main>
    </>
  );
}
