import Custom from "@/components/Custom/Custom";
import NavbarCustom from "@/components/Navbar/NavbarCustom";
import Head from "next/head";
import React from "react";

function OrderSolarRoof() {
  return (
    <>
      <div>
        <Head>
          <title>Solar Roof Order | Tesla</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/icon.png" />
        </Head>
      </div>

      <main>
        <NavbarCustom />
        <Custom
          bgImageOne="ModelSolarRoof.jpeg"
          bgImageTwo="ModelSolarRoof2.jpeg"
          bgImageThree="ModelSolarRoof3.jpg"
          bonus="Install Solar Roof and power your home with a fully integrated solar and energy storage system. The glass solar tiles and steel roofing tiles look great up close and from the street, complementing your home’s natural styling."
          title="Power Everything"
          btnCenter="Continue to Payment"
          delivery="Est. Delivery: Apr – Jun 2023"
          range=""
          subRange=""
          speed=""
          subSpeed=""
          seconds=""
          subSeconds=""
          price="$ 3,990"
          subPrice="$ 19,990 Full House"
        />
      </main>
    </>
  );
}

export default OrderSolarRoof;
