import Custom from "@/components/Custom/Custom";
import NavbarCustom from "@/components/Navbar/NavbarCustom";
import Head from "next/head";
import React from "react";

function CustomS() {
  return (
    <>
      <div>
        <Head>
          <title>Design Your Model S | Tesla</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/icon.png" />
        </Head>

        <main>
          <NavbarCustom />
          <Custom
            bgImageOne="ModelSCustom.jpeg"
            bgImageTwo="ModelSCustom2.jpeg"
            bgImageThree="ModelSCustom3.jpeg"
            bonus="$7,500 Federal Tax Credit New Model S vehicles qualify for a federal tax credit for eligible buyers. This $7,500 credit is in effect for deliveries taken before an update to the federal guidance, which Treasury and the IRS intend to issue no later than March 31, 2023.See Details"
            title="Model S"
            btnCenter="Continue to Payment"
            delivery="Est. Delivery: Apr – Jun 2023"
            range="405mi"
            subRange="Range (EPA est.)"
            speed="149mph"
            subSpeed="Top Speed"
            seconds="3.1sec"
            subSeconds="0-60 mph"
            price="$ 99,990 Vehicle Price "
            subPrice="$ 93,090 After Potential Savings"
          />
        </main>
      </div>
    </>
  );
}

export default CustomS;
