"use client";

import NavbarCustom from "@/components/Navbar/NavbarCustom";
import Head from "next/head";
import React from "react";
import Custom from "@/components/Custom/Custom";

type CustomProps = {
  Custom: string;
};

function Custom3() {
  return (
    <>
      <div>
        <Head>
          <title>Design Your Model 3 | Tesla</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/icon.png" />
        </Head>
      </div>

      <main>
        <NavbarCustom />
        <Custom
          bgImageOne="Model3Custom.jpeg"
          bgImageTwo="Model3Custom2.jpeg"
          bgImageThree="Model3Custom3.jpeg"
          bonus="New Model 3 and Model Y vehicles qualify for a federal tax credit for eligible buyers. This $7,500 credit is in effect for deliveries taken before an update to the federal guidance, which Treasury and the IRS intend to issue no later than March 31, 2023.See Details"
          title="Model 3"
          btnCenter="Continue to Payment"
          delivery="Est. Delivery: Mar 2023"
          range="272mi"
          subRange="Range (EPA est.)"
          speed="140mph"
          subSpeed="Top Speed"
          seconds="5.8sec"
          subSeconds="0-60 mph"
          price="$ 42,990 Vehicle Price "
          subPrice="$ 29,290 After Potential Savings"
        />
      </main>
    </>
  );
}

export default Custom3;
