"use client";

import NavbarWhite from "@/components/Navbar/NavbarWhite";
import Head from "next/head";
import React from "react";
import { Fade } from "react-awesome-reveal";
import { useRouter } from "next/router";

function Model3() {
  const router = useRouter();
  const sectionStyle = {
    backgroundImage: `url("/Article/Model3.jpeg")`,
  };

  return (
    <>
      <div>
        <Head>
          <title>Model 3 | Tesla</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/icon.png" />
        </Head>

        <main
          style={sectionStyle}
          className="w-full h-screen bg-cover bg-center bg-no-repeat flex flex-col justify-between items-center overflow-hidden"
        >
          <div className="absolute top-0 right-0 left-0">
            <NavbarWhite />
          </div>

          <div className="pt-[15vh] text-center">
            <h1 className="text-white text-4xl font-bold">Model 3</h1>
            <p className="text-white text-xl">Schedule a Demo Drive</p>
            <p className="border border-white bottom"></p>
          </div>

          <div className="mb-[10vh] lg:flex items-center justify-center">
            <div className="flex text-white items-center justify-center w-full my-5">
              <Fade delay={100}>
                <div className="detail-show">
                  <h2 className="md:text-2xl text-md font-bold">3. 1 s</h2>
                  <p className="md:text-sm text-[10px] font-bold">0-60 mph*</p>
                </div>
              </Fade>

              <Fade delay={200}>
                <div className="detail-show">
                  <h2 className="md:text-2xl text-md font-bold">358 mi</h2>
                  <p className="md:text-sm text-[10px] font-bold">
                    Range(Epa est.)
                  </p>
                </div>
              </Fade>

              <Fade delay={300}>
                <div className="detail-show">
                  <h2 className="md:text-2xl text-md font-bold">AWD</h2>
                  <p className="md:text-sm text-[10px] font-bold">Dual Motor</p>
                </div>
              </Fade>
            </div>

            <Fade delay={500}>
              <div className="flex flex-col items-center md:flex-row md:justify-center">
                <button
                  onClick={() => router.push("/DemoDrive/DemoDrive")}
                  className="btn-white my-1 md:my-0"
                >
                  Demo Drive
                </button>
              </div>
            </Fade>
          </div>
        </main>
      </div>
    </>
  );
}

export default Model3;
