"use client";

import Navbar from "@/components/Navbar/Navbar";
import { SunIcon, CurrencyDollarIcon } from "@heroicons/react/24/solid";
import Head from "next/head";
import React from "react";
import { Fade } from "react-awesome-reveal";
import { useRouter } from "next/router";

function SolarPanel() {
  const sectionStyle = {
    backgroundImage: `url("/Article/SolarPanel.jpeg")`,
  };
  const router = useRouter();

  return (
    <>
      <div>
        <Head>
          <title>Solar Panels | Tesla</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/icon.png" />
        </Head>
        <main
          style={sectionStyle}
          className="w-full h-screen bg-cover bg-center bg-no-repeat flex flex-col justify-between items-center overflow-hidden"
        >
          <div className="absolute top-0 right-0 left-0">
            <Navbar />
          </div>

          <div className="pt-[15vh] text-center">
            <h1 className="text-black text-4xl font-bold">
              Solar for Existing Roofs
            </h1>
          </div>

          <div className="mb-[10vh] lg:flex items-center justify-center">
            <div className="flex text-white items-center justify-center w-full my-5">
              <Fade delay={100}>
                <div className="detail-show">
                  <span className="flex items-center justify-center">
                    <SunIcon className="md:w-8 md:h-8 w-6 h-6" />
                  </span>
                  <p className="md:text-sm text-[10px] font-bold">
                    Convert Sunlight to Energy
                  </p>
                </div>
              </Fade>

              <Fade delay={200}>
                <div className="detail-show">
                  <span className="flex items-center justify-center">
                    <CurrencyDollarIcon className="md:w-8 md:h-8 w-6 h-6" />
                  </span>
                  <p className="md:text-sm text-[10px] font-bold">
                    Guaranteed Lowest
                  </p>
                  <p className="md:text-sm text-[10px] font-bold">
                    Price for Solar
                  </p>
                </div>
              </Fade>

              <Fade delay={300}>
                <div className="detail-show">
                  <h2 className="md:text-2xl text-md font-bold">24/7</h2>
                  <p className="md:text-sm text-[10px] font-bold">
                    Energy Monitoring
                  </p>
                </div>
              </Fade>
            </div>

            <Fade delay={500}>
              <div className="flex flex-col items-center md:flex-row md:justify-center">
                <button
                  onClick={() => router.push("/SolarPanels/OrderSolarPanel")}
                  className="btn-white my-1 md:my-0"
                >
                  Order Now
                </button>
              </div>
            </Fade>
          </div>
        </main>
      </div>
    </>
  );
}

export default SolarPanel;
