import Custom from "@/components/Custom/Custom";
import NavbarCustom from "@/components/Navbar/NavbarCustom";
import Head from "next/head";
import React from "react";

function OrderPowerWall() {
  return (
    <>
      <div>
        <Head>
          <title>PowerWall Order | Tesla</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/icon.png" />
        </Head>
      </div>

      <main>
        <NavbarCustom />
        <Custom
          bgImageOne="PowerWall.jpeg"
          bgImageTwo="PowerWall2.jpeg"
          bgImageThree="PowerWall3.jpeg"
          bonus="All Tesla solar systems integrate with Powerwall, a compact home battery that reduces your reliance on the grid by storing your solar energy for use when the sun isn’t shining. You can add additional Powerwall units to your order to further lower your carbon footprint and to prepare your home for power outages. Chat with an energy advisor to ask any questions about Tesla solar and Powerwall."
          title="Power Everything"
          btnCenter="Continue to Payment"
          delivery="Est. Delivery: Apr – Jun 2023"
          range=""
          subRange=""
          speed=""
          subSpeed=""
          seconds=""
          subSeconds=""
          price="$ 3,990"
          subPrice="$ 9,990 Full House"
        />
      </main>
    </>
  );
}

export default OrderPowerWall;
